// cdb_parser.h
// Declaration of the CDB parser for SDCC compiler output files.
//
// This file declares the cdb_parser class, which parses C debug information
// files (CDB) generated by the SDCC compiler, extracting module, function,
// symbol, type, and line information into cdbg_info structures.
//
// Copyright 2025 Tomaz Stih. All rights reserved.
// MIT License.
#pragma once

#include <sdcc/parser.h>
#include <sdcc/cdbg_info.h>

namespace sdcc {

// Parses C debug information files from the SDCC compiler.
class cdb_parser : public parser_impl<cdbg_info_module> {
protected:
    bool do_parse(const std::string& path) override;

private:
    void parse_line(std::string_view line);
    void parse_module(std::string_view content);
    void parse_function(std::string_view content);
    void parse_symbol(std::string_view content);
    void parse_type(std::string_view content);
    void parse_line_info(std::string_view content);

    // Track current module for assigning functions, symbols, etc.
    std::string current_module_;
};

} // namespace sdcc